(* generated by dune *)

(** @canonical Llamaml.Alloc *)
module Alloc = Llamaml__Alloc

(** @canonical Llamaml.Cgraph *)
module Cgraph = Llamaml__Cgraph

(** @canonical Llamaml.Cordis_plugin *)
module Cordis_plugin = Llamaml__Cordis_plugin

(** @canonical Llamaml.Gguf *)
module Gguf = Llamaml__Gguf

(** @canonical Llamaml.Kv_cache *)
module Kv_cache = Llamaml__Kv_cache

(** @canonical Llamaml.Model *)
module Model = Llamaml__Model

(** @canonical Llamaml.Ops *)
module Ops = Llamaml__Ops

(** @canonical Llamaml.Quant *)
module Quant = Llamaml__Quant

(** @canonical Llamaml.Sampler *)
module Sampler = Llamaml__Sampler

(** @canonical Llamaml.Server *)
module Server = Llamaml__Server

(** @canonical Llamaml.Tensor *)
module Tensor = Llamaml__Tensor

(** @canonical Llamaml.Tokenizer *)
module Tokenizer = Llamaml__Tokenizer

(** @canonical Llamaml.Types *)
module Types = Llamaml__Types

module Llamaml__ = struct end
[@@deprecated "this module is shadowed"]
